# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
url: https://YangLIU0803.github.io
baseurl: /
title: Little Monster Five's Site
description: >
    Little Monster Five's Site | 小怪兽废物的个人主页


## => Language and Timezone
##############################
lang: zh
timezone: Asia/Shanghai


## => Author and Social
##############################
author:
  name: Little Monster Five
  email: 



## => GitHub Repository
##############################
repository: YangLIU0803/YangLIU0803.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /blog
  archive: /blog/archive.html
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0


## => Paginate分页，每页最多显示10篇文章
##############################
paginate: 10
paginate_path: /blog/page:num


## => Comments
##############################
comments:
  provider: disqus
  disqus:
    shortname: YangLIU0803-github-io


## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id: STOPxUpJ8jNzHhTUe8gMMVsR-gzGzoHsz
    app_key: Gt91Y1mEt9dsksEri0RdXUUx
    app_class: Blog


## => Analytics
##############################
analytics:
  provider: google
  google:
    tracking_id: 


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


## => Server
##############################
server_url: "0.0.0.0"
port: 4001
